---
- name: Instalacao Docker
  hosts: localhost
  become: true


tasks:
  - name: update S.O
    apt:
      update_cache: yes
      upgrade: dist

  - name: install Docker
    apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      

  - name: add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Instalar docker
    apt: 
      name: docker-ce
      state: latest

  - name: Instalar Docker Compose
    command: >
      curl -L "https://github.com/docker/compose/releases/download/2.23.0/docker-compose-$(uname -s)-$(uname -m)"
      -o /usr/local/bin/docker-compose
      creates=/usr/local/bin/docker-compose
    args:
      creates: /usr/local/bin/docker-compose
    become: yes

  - name: Tornar Docker Compose executável
    file:
      path: /usr/local/bin/docker-compose
      mode: '0755'
    become: yes

  - name: Iniciar e habilitar o serviço Docker
    systemd:
      name: docker
      state: started
      enabled: yes
    

  - name: Adicionar o usuário atual ao grupo docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Clone do repositório do GitHub
    git:
      repo: https://github.com/nicklima-amigos/football-mm.git
      dest: /opt/appfootball
      clone: yes
      force: yes

  - name: Executar Docker Compose
    command: docker-compose up -d
    args:
      chdir: /opt/appfootball/football-mm