packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}

variable "client_id" {
  type    = string
  default = "8128e4ad-61ed-4117-8d00-4c5a83ced768"
}

variable "client_secret" {
  type    = string
  default = "yUd8Q~tF_4mZgpSrI6QAOGbux5Tw1R4Z58xWRblp"
}

variable "subscription_id" {
  type    = string
  default = "e9fa120a-50d5-41c7-905d-4fce76423744"
}

variable "tenant_id" {
  type    = string
  default = "e2bb3629-2e05-4ebf-8637-82a2932193f7"
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "engineering"
  }
  client_id                         = "${var.ARM_CLIENT_ID}"
  client_secret                     = "${var.ARM_CLIENT_SECRET}"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "19.04"
  location                          = "East US"
  managed_image_name                = "packerimagefootball"
  managed_image_resource_group_name = "football-mm"
  os_type                           = "Linux"
  subscription_id                   = "${var.ARM_SUBSCRIPTION_ID}"
  temp_resource_group_name          = "packer-rg"
  tenant_id                         = "${var.ARM_TENANT_ID}"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "file" {
    destination     = "/tmp/ansible"
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    source          = "./ansible"
  }

  provisioner "ansible" {
    playbook_file = "/tmp/ansible/playbook.yml"
  }

}
