name: Run Azure Login with OIDC

on:
  push:
    branches: [ feat/azure-terraform-ci ]

  pull_request:
    branches: [ feat/azure-terraform-ci ]

permissions:
    id-token: write
    contents: read

jobs: 
  azure-build-terraform:
    runs-on: ubuntu-latest
    steps:

      - name: Az CLI login
        uses: azure/login@v1
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform apply
        run: |
            cd terraform
            terraform init
            terraform plan -out plan.tf
            terraform apply -auto-approve plan.tf