name: Build and Push Docker CI
on:
  push:
    branches:
      - main
      - chore/variables-azure-packer

jobs:
  docker-CI:
    name: "Docker-CI"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurar ambiente Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Construir imagem Docker
      run: |
        docker build -t football-mm:${{ github.run_number }} .

    - name: Marcar imagem com a versão do repositório
      run: |
        REF_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///' | sed 's/\//-/g')
        docker tag football-mm:${{ github.run_number }} football-mm:latest
        docker tag football-mm:${{ github.run_number }} football-mm:$REF_NAME

    - name: Enviar imagem para o Docker Hub
      run: |
        docker push football-mm:latest
        docker push football-mm:${{ github.ref }}
